import { createHash } from 'node:crypto';
import { cp, mkdir, mkdtemp, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { filterCollections, periodStarts } from '../web/static/railway-filter.mjs';

export { filterCollections, parseYear, periodStarts } from '../web/static/railway-filter.mjs';

const MAX_ASSET_BYTES = 25 * 1024 * 1024;
const MARKER = '.location3-generated';
const SOURCES = { railroads: 'N05-24_RailroadSection2.geojson', stations: 'N05-24_Station2.geojson' };

function contains(parent, child) {
  const path = relative(parent, child);
  return path === '' || (!path.startsWith('..') && !isAbsolute(path));
}

async function exists(path) {
  try { await stat(path); return true; }
  catch (error) { if (error.code === 'ENOENT') return false; throw error; }
}

export async function prepareData({ inputDir, staticDir, outputDir, maxAssetBytes = MAX_ASSET_BYTES }) {
  inputDir = resolve(inputDir);
  staticDir = resolve(staticDir);
  outputDir = resolve(outputDir);
  for (const source of [inputDir, staticDir]) {
    if (contains(outputDir, source) || contains(source, outputDir)) {
      throw new Error('Generated output must be separate from source data and static files.');
    }
  }
  if (await exists(outputDir) && !await exists(join(outputDir, MARKER))) {
    throw new Error(`Refusing to replace an unmarked output directory: ${outputDir}`);
  }

  const collections = {};
  for (const [kind, filename] of Object.entries(SOURCES)) {
    const collection = JSON.parse(await readFile(join(inputDir, filename), 'utf8'));
    if (collection?.type !== 'FeatureCollection' || !Array.isArray(collection.features)) {
      throw new Error(`Invalid GeoJSON: ${filename}`);
    }
    collections[kind] = collection;
  }

  // Build separately so a failed generation leaves the previous deployable data intact.
  await mkdir(dirname(outputDir), { recursive: true });
  const staging = await mkdtemp(join(dirname(outputDir), '.location3-assets-'));
  const files = new Set();
  let bytes = 0;
  try {
    await cp(staticDir, staging, { recursive: true });
    await mkdir(join(staging, 'datasets'), { recursive: true });
    await writeFile(join(staging, MARKER), 'Generated by scripts/prepare-data.mjs\n');

    async function store(collection) {
      const body = JSON.stringify(collection);
      const size = Buffer.byteLength(body);
      if (size > maxAssetBytes) {
        throw new Error(`GeoJSON asset is ${size} bytes, exceeding the ${maxAssetBytes}-byte asset limit.`);
      }
      const hash = createHash('sha256').update(body).digest('hex');
      const path = `/datasets/${hash}.geojson`;
      if (!files.has(path)) {
        await writeFile(join(staging, path.slice(1)), body);
        files.add(path);
        bytes += size;
      }
      return { path, count: collection.features.length, bytes: size };
    }

    async function storePair(pair) {
      return { railroads: await store(pair.railroads), stations: await store(pair.stations) };
    }

    const manifest = { version: 1, all: await storePair(collections), periods: [] };
    for (const startYear of periodStarts(collections)) {
      manifest.periods.push({ startYear, ...await storePair(filterCollections(collections, startYear)) });
    }
    await writeFile(join(staging, 'datasets/manifest.json'), JSON.stringify(manifest));
    // The marker is only for local rebuild safety; keep it out of public static assets.
    await writeFile(join(staging, '.assetsignore'), `${MARKER}\n.assetsignore\n`);

    if (await exists(outputDir)) {
      const previous = `${staging}-previous`;
      await rename(outputDir, previous);
      try { await rename(staging, outputDir); }
      catch (error) { await rename(previous, outputDir); throw error; }
      await rm(previous, { recursive: true, force: true });
    } else {
      await rename(staging, outputDir);
    }
    return { periods: manifest.periods.length, files: files.size, bytes, manifest };
  } finally {
    await rm(staging, { recursive: true, force: true });
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const { values } = parseArgs({ options: {
      'input-dir': { type: 'string', default: 'N05-24_GML/UTF-8' },
      'static-dir': { type: 'string', default: 'web/static' },
      'output-dir': { type: 'string', default: '.generated/assets' },
    } });
    const result = await prepareData({ inputDir: values['input-dir'], staticDir: values['static-dir'], outputDir: values['output-dir'] });
    console.log(`Prepared ${result.periods} periods, ${result.files} GeoJSON assets (${(result.bytes / 1024 / 1024).toFixed(1)} MiB) in ${values['output-dir']}`);
  } catch (error) {
    console.error(`Failed to prepare railway data: ${error.message}`);
    process.exitCode = 1;
  }
}
